[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "scipy",
    "click",
    "blosc",
    "fair-esm",
    "torch",
    "statsmodels"
]
build-backend = "setuptools.build_meta"
